on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p snapshot/something-1
          mkdir -p snapshot/something-2
          touch snapshot/something-1/file1.txt
          touch snapshot/something-2/file2.txt
      # - uses: actions/upload-artifact@v4
      #   with:
      #     path: file*
      - uses: actions/github-script@v7
        with:
          script: |
            const { readdirSync } = require('fs')
            const artifact = require('@actions/artifact')

            const getDirectories = source =>
              readdirSync(source, { withFileTypes: true })
                .filter(dirent => dirent.isDirectory())
                .map(dirent => dirent.name)

            const allDirs = getDirectories("snapshot")

            for (const f of allDirs) {
              const {id, size} = await artifact.uploadArtifact(
                // name of the artifact
                f,
                ['./snapshot/'+f+'/*'],
                { retentionDays: 30 }
              )
            }
