on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p snapshot/something-1
          mkdir -p snapshot/something-2
          touch snapshot/something-1/file1.txt
          touch snapshot/something-2/file2.txt

      - run: npm install @actions/artifact@2.2.2

      - uses: actions/github-script@v7
        with:
          script: |
            const { readdirSync } = require('fs')
            const { DefaultArtifactClient } = require('@actions/artifact')
            const artifact = new DefaultArtifactClient()
            
            const getDirectories = source =>
              readdirSync(source, { withFileTypes: true })
                .filter(dirent => dirent.isDirectory())
                .map(dirent => dirent.name)

            const allDirs = getDirectories("snapshot")

            console.log("allDirs:", allDirs)

            for (const f of allDirs) {
              console.log("f:", f)

              const {id, size} = await artifact.uploadArtifact(
                `${f}`,
                [ `./snapshot/${f}/*` ],
                { retentionDays: 30 }
              )
            }
