on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p snapshot/something-1
          mkdir -p snapshot/something-2
          touch snapshot/something-1/file1.txt
          touch snapshot/something-2/file2.txt

      - run: npm install @actions/artifact@2.2.2

      - uses: actions/github-script@v7
        with:
          script: |
            const { readdirSync } = require('fs')
            const { DefaultArtifactClient } = require('@actions/artifact')
            const artifact = new DefaultArtifactClient()
            const ls = d => readdirSync(d, { withFileTypes: true })

            for (const dir of ls("snapshot").filter(f => f.isDirectory()).map(f => f.name)) {
              const {id, size} = await artifact.uploadArtifact(
                `${dir}`,
                ls(`./snapshot/${dir}`).map(f => `./snapshot/${dir}/${f.name}`),
                `./snapshot/${dir}`,
                { retentionDays: 30 }
              )
            }
